version: '2'
services:
  tg_dj:
    build: .
    volumes:
      - ./config.ini:/config.ini:ro
      - ./data:/data
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
